FROM node:22-alpine3.21 as builder

WORKDIR /app

COPY . .
RUN npm install
RUN npm run build


FROM nginx:1.29.1-alpine

COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
